server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
  sql:
    init:
      mode: always
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Loans Service for Eazy bank"
    version: "1.0-RELEASE"
logging:
  level:
    com:
      banks:
        loans: DEBUG