services:
  accounts:
    image: "karthik89k/accounts:s1"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank-network
  loans:
    image: "karthik89k/loans:s1"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank-network
  cards:
    image: "karthik89k/cards:s1"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank-network
networks:
  eazybank-network:
    driver: "bridge"